# Generated by Django 2.0 on 2022-05-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acusa_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_matric_no', models.CharField(editable=False, max_length=20)),
                ('student_message', models.TextField(editable=False, max_length=3000)),
                ('reply_student', models.TextField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('years', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dues_Paymet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=20)),
                ('paid_dues', models.BooleanField(default=False)),
                ('paid', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('event_day', models.CharField(max_length=2)),
                ('event_month', models.CharField(max_length=3)),
                ('event_time', models.CharField(max_length=15)),
                ('event_venue', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('event_picture', models.FileField(upload_to='events_picture')),
            ],
        ),
        migrations.CreateModel(
            name='Exco_Brief_Writeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('exco_post', models.CharField(max_length=20)),
                ('write_up', models.CharField(max_length=200)),
                ('small_picture', models.FileField(upload_to='small_picture')),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50, unique=True)),
                ('picture', models.FileField(upload_to='excos')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Former_Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50, unique=True)),
                ('picture', models.FileField(upload_to='excos')),
            ],
        ),
        migrations.CreateModel(
            name='Former_Executive_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Message_Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=20, unique=True)),
                ('messages', models.ManyToManyField(blank=True, null=True, to='chat.Acusa_Message')),
            ],
        ),
        migrations.CreateModel(
            name='Message_Algorithm2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=20)),
                ('student_message', models.TextField(max_length=3000)),
                ('reply_student', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('news_date', models.CharField(max_length=11)),
                ('speaker_or_source', models.CharField(max_length=20)),
                ('half_description', models.TextField(max_length=100)),
                ('full_description', models.TextField(max_length=5000)),
                ('news_picture', models.FileField(upload_to='news_picture')),
            ],
        ),
        migrations.CreateModel(
            name='Past_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('level', models.IntegerField(max_length=11)),
                ('course_title', models.CharField(max_length=50)),
                ('fl', models.FileField(upload_to='past_question_file')),
            ],
        ),
        migrations.CreateModel(
            name='SessionalPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(max_length=200, unique=True)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('matric_no', models.CharField(max_length=20, unique=True)),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=11)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField()),
                ('mode_of_entry', models.CharField(max_length=24)),
                ('all_acusa_payment', models.TextField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_matric_no', models.CharField(max_length=20, unique=True)),
                ('reply_student', models.CharField(max_length=3000)),
                ('student_message', models.CharField(max_length=3000)),
            ],
        ),
    ]
