# Generated by Django 2.0 on 2022-05-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_acusa_message_department_dues_paymet_event_exco_brief_writeup_executive_faculty_former_executive_for'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Dues_Paymet',
        ),
        migrations.DeleteModel(
            name='Exco_Brief_Writeup',
        ),
        migrations.DeleteModel(
            name='Executive',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Former_Executive',
        ),
        migrations.DeleteModel(
            name='Former_Executive_Set',
        ),
        migrations.RemoveField(
            model_name='message_algorithm',
            name='messages',
        ),
        migrations.DeleteModel(
            name='Message_Algorithm2',
        ),
        migrations.DeleteModel(
            name='Past_Question',
        ),
        migrations.DeleteModel(
            name='SessionalPayment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Students_Message',
        ),
        migrations.DeleteModel(
            name='Acusa_Message',
        ),
        migrations.DeleteModel(
            name='Message_Algorithm',
        ),
    ]
